[toolchain]
package_manager = "yarn"
anchor_version = "0.32.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
staking = "6tPaSkVKra9nSFdvFEmiQKLH88WqeAzkjtWqgJAPn4N9"

[programs.mainnet]
staking = "6tPaSkVKra9nSFdvFEmiQKLH88WqeAzkjtWqgJAPn4N9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "/home/dev/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
